custom:
  - "https://litecoinspace.org/address/Lcd6pCPiVw9GH2MAaGkR8TX39EtL2LzFoa"
  - "https://solscan.io/account/EfwivXazedEw2kL2et92NKDkT3qrQ6pdxA8Bs7RKYRuN"
  - "https://etherscan.io/address/0x85C09A302CBB42a321E737E6E4dDAC0Eebc4ac3E"
  - "https://mempool.space/address/bc1qlhym0f0lejwlhd47gext8g7fgej366j7z85vvx"