[package]
name = "vertb1/cascade"
description = "An open-source Luau UI library based on macOS Sequoia."
license = "MIT"
authors = ["vertb1"]
version = "1.2.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = [
    "src/*",
    "default.project.json",
    "wally.lock",
    "wally.toml",
    "README.md",
]

[dependencies] # Im not sure if wally handles packages correctly, so im not gonna recommend to use wally installation method. Plus i dont feel like updating this every time.
Fusion = "elttob/fusion@^0.3"