name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        
      - name: Install Tools
        run: aftman install --no-trust-check
        
      - name: Build Project
        run: pcmp Debug
        
      - name: Resolve Release Tag
        id: vars
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create Release Notes
        run: |
          mkdir -p generated/release
          echo "## eo2x - ${{ env.tag }}" > generated/release/RELEASE_NOTES.md
          echo "Changes in this build:" >> generated/release/RELEASE_NOTES.md
          git log -1 --pretty=format:"- %s" >> generated/release/RELEASE_NOTES.md

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag }}
          name: "eo2x - ${{ env.tag }}"
          body_path: generated/release/RELEASE_NOTES.md
          files: generated/debug/dist.luau
          draft: false
          prerelease: false
